### PR TITLE
Updates the README files for various exercises

### PR DESCRIPTION
**Pull request by Zureka**
This is the result of running the `./bin/configlet generate` command against the master branch of the problem-specifications repository. Please let me know if there is a better way for merging these types of changes.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Hi! Actually, to update the docs we have a customs step (in which some readme files are patched). You can run this custom step by running the `update-docs.sh` command in the root directory.

**Comment by Zureka** [comment]
@ErikSchierboom Ahh I see, I did get a little confused when I noticed all of the occurrences of the word "method" changed to "function" in all of these C# projects. 

In terms of updating these README files, would it be better to do them one exercise at a time with any potential generator updates that might be necessary? Or is a batch README update like this acceptable?

**Comment by Zureka** [comment]
I mean... I would appreciate some Hacktoberfest PR's 😉. But I wasn't sure if the README updates would reflect changes for exercises that needed to be re-generated. 

I can do individual PR's if that's what you prefer.

**Comment by ErikSchierboom** [comment]
I'm fine either way, whichever suits you best.

**Comment by Zureka** [comment]
I'll close this PR and update the README files as part of any exercise updates that are necessary. That way I can familiarize myself with running/modifying the generators.

**Comment by ErikSchierboom** [comment]
Remember that it is also fine to just send PR's with just the README updates. As I think most exercises will have been updated to the latest canonical data.

**Pull request closed without merging**
