### PR TITLE
Update exercises to the latest canonical data

### PR DESCRIPTION
**Pull request by robkeim**
I just ran the generator and it looks like there have been a fair amount of changes to canonical data that we haven't integrated yet. This batch contains the "trivial changes" requiring no updates to the code. The remaining exercises will require some updates.

### CODE REVIEW

**Comment by robkeim** [comment]
Updated Food Chain as well

**Comment by robkeim** [comment]
Updated House

**Comment by ErikSchierboom** [comment]
Great work! I'll wait for the CI to become green.

**Comment by robkeim** [comment]
I updated a few more tests that required minor changes as well. The following tests are still out-of-date and need to be updated:
- AllYourBase (changed to using "error"  structure)
- BeerSong (changed to returning an array which isn't currently being formatted multi-line. That means the test validating the entire song is a reaaalllllyyyyy long line :) )
- NthPrime (changed to using "error" structure)

**Comment by ErikSchierboom** [comment]
Thanks a lot! 🎉  Do you want to create separate issues for the out-of-date exercises?

**Comment by robkeim** [comment]
Sounds good @ErikSchierboom let's keep track of those updates in #488.

**Pull request merged**
