### PR TITLE
dependabot: simplify configuration

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by robkeim** [comment]
IMO, we should combine this change with removing the script to generate this file as well as removing it from the new exercise template.

That said, I've got two concerns about this:
1. I'm not sure it's working correctly in the FSharp track as I called out in https://github.com/exercism/fsharp/pull/681
2. Given we have all of the PRs opened by dependabot, I'm wondering if it makes sense to push a change to this file where we enable auto-close on the existing configuration in order to get the existing PRs closed before simplifying the configuration.

**Comment by ErikSchierboom** [comment]
1. I think it is working: https://github.com/exercism/fsharp/pull/681#issuecomment-467889646 (you just don't see everything at once)
1. I'm not sure what actually will happen when we merge this. Will the existing PR's be automatically merged like `accumulate` did before?

**Comment by robkeim** [comment]
@ErikSchierboom I don't know what will happen... do you think it's safer to merge a change first to cleanup the existing PRs, then simplify the configuration? I've got that change ready on my side.

I'd like to avoid having to cleanup 100s of PRs by hand :)

**Comment by ErikSchierboom** [comment]
@robkeim Sure. Let's try it :)

**Comment by robkeim** [comment]
The PR to add auto merge everywhere is here: #1238

**Comment by ErikSchierboom** [comment]
@robkeim I've rebased and remove the script and README instructions.

**Comment by robkeim** [comment]
Looks good... we can merge this as soon as the backlog of PRs are merged and the CI is green.

**Comment by robkeim** [comment]
I'm seeing several PRs at least in a "failed" state:
https://github.com/exercism/csharp/pull/1221

> Dependabot tried to update this pull request, but something went wrong. We're looking into it, but in the meantime you can retry the update by commenting `@dependabot rebase`.

I'll try merging a few by hand to see if that unblocks anything

**Comment by greysteil** [comment]
Hey, I've been seeing the errors that caused the above - they're all rate limit issues from GitHub.

I think the simplest way forward here would be for you to merge this PR and then for me to close all of the current PRs. Would that work?

**Comment by ErikSchierboom** [comment]
Sure. I've merged this.

**Comment by ErikSchierboom** [comment]
Oh, and thanks for all the help!

**Comment by greysteil** [comment]
Great - will sort out all the old PRs from my side. Give me a few minutes 🙂

**Pull request merged**
