### PR TITLE
Implement new exercise: high-scores

### PR DESCRIPTION
**Pull request by learningsam20**
Implementing new exercise for high-scores problem

### CODE REVIEW

**Comment by B1tF8er** [comment]
No worries if @learningsam20 finished it first, I can stop working on this

**Comment by ErikSchierboom** [comment]
@B1tF8er I think you can continue working on it, this PR is far from complete.

**Comment by B1tF8er** [comment]
Ok, I will continue to work on this

**Comment by robkeim** [comment]
@learningsam20 I'm going to go ahead and close this PR for now. If you continue working on this feel free to re-open the PR when it's ready.

**Pull request closed without merging**
