### PR TITLE
Clock test generator should render Assert.Equals #435

### PR DESCRIPTION
**Pull request by R0nd**

### CODE REVIEW

**Comment by R0nd** [comment]
Fixes #435

**Comment by ErikSchierboom** [comment]
@R0nd Thank you for your contribution! Your PR as is does contain the desired end result, however you didn't actually change the test generator used to generate the test file. You can read more about the test generators in this document: https://github.com/exercism/csharp/blob/master/docs/GENERATORS.md

In the end, you should thus modify the generator for the clock exercise, which source is found here: https://github.com/exercism/csharp/blob/master/generators/Exercises/Clock.cs Once you have it modified, you then execute the generators project and see if the contents of the `exercises/clock/ClockTest.cs` file matches that what you want.

If you have any questions, feel free to ask them in the [Gitter room](https://gitter.im/exercism/xcsharp).

**Comment by jpreese** [comment]
Hello @R0nd! Did you have any questions about this PR?

**Comment by jpreese** [comment]
Closing PR based on @R0nd's response in #435

**Pull request closed without merging**
