### PR TITLE
Rename test classes to ClassNameTests (plural) instead of ClassNameTest (singular)

### PR DESCRIPTION
**Pull request by robkeim**
A Luhn update snuck in as well...

Some more context can be found on this PR here:
https://github.com/exercism/v3/pull/782#discussion_r383016697

### CODE REVIEW

**Comment by robkeim** [comment]
Any idea how to debug this build error @ErikSchierboom?

**Comment by ErikSchierboom** [comment]
@robkeim No, but the issue has been reported: https://github.com/exercism/configlet/issues/173 I'll try and run the branch locally then.

**Comment by robkeim** [comment]
Good catch, updated!

**Comment by ErikSchierboom** [comment]
Thanks a ton for doing this @robkeim! We should probably do the same for the F# track, and then for the v3 stuff.

**Comment by robkeim** [comment]
Here are the changes for F#:
https://github.com/exercism/fsharp/pull/778

**Pull request merged**
