### PR TITLE
Sync docs: configlet sync -u -y --docs

### PR DESCRIPTION
**Pull request by IsaacG**
Followup from running configlet fmt
See also
https://forum.exercism.org/t/configlet-4-0-0-beta-11-breaks-c-track-builds/

### CODE REVIEW

**Comment by IsaacG** [comment]
This may be blocked on the `configlet fmt` PR. Once that PR lands, the configlet will be happier.

**Comment by ErikSchierboom** [comment]
This needs to be rebased

**Comment by IsaacG** [comment]
> I've merged the other PR. This now needs to be rebased I guess

Done!

**Comment by ErikSchierboom** [comment]
One tiny merge conflict (sorry about that)

**Comment by IsaacG** [comment]
Re-synced

**Review by ErikSchierboom — APPROVED** [review]
Great! Thanks

**Pull request merged**
