### PR TITLE
WIP Update prime factors to use longs

### LINKED ISSUE #1309: Inherent flaw in PrimeFactor exercise
I understand the motivation behind implementing a test which exceeds the 32-bit range:

```
    [Fact]
    public void Factors_include_a_large_prime()
    {
        Assert.Equal(new[] { 11, 9539, 894119 }, PrimeFactors.Factors(93819012551));
    }
```

but I think it is misguided at best if not encouraging questionable practice to then have the solution template mixing 32- and 64-bit (`public static int[] Factors(long number)`) and the tests all testing against an `int` instead of `long`. If the student is meant to implement support for 64-bit numbers it should also test against 64-bit values.

### PR DESCRIPTION
**Pull request by robkeim**
This change causes all of the ints to be treated as longs throughout the rest of the exercises. I left the other exercises out of this WIP PR so it makes it easier to see what changes I made.

@ErikSchierboom do you have an idea what I'm doing wrong?

Fixes #1309

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@robkeim You're not really doing anything wrong, it's just that JSON.net by default will deserialize numbers to a `long`, as some numbers might not fit into a `int`. 

Now what to do about this. There are several options I feel:

1. At the places where a long is needed, we render it as a long string instead of relying on the automatic rendering (which has an effect on all exercises).
1. We could plug a custom JsonConverter into our deserialization, which correctly identifies if a value should actually be converted to an integer instead of a long. I have some experience with this, so I can help here.

I think the second one is a little bit nicer, but also a bit more work. I'm happy to help here though. What do you think?

**Comment by robkeim** [comment]
I'm also in favor of the second solution. I poked around a bit and tried to understand how the deserialization works, but I don't see where/how we can add a custom JsonConverter to parse integer values correctly.

I'm not sure what's the best way to proceed here. Did you want to try to make the change or did you want to try to explain to me where the change needs to be made and then have me do it? Either way works for me.

**Comment by ErikSchierboom** [comment]
> Did you want to try to make the change [...]

I think this is probably the easiest option. I'll let you know when I have anything for you to work with!

**Comment by robkeim** [comment]
Sounds good, if there's anything I can do let me know!

**Comment by ErikSchierboom** [comment]
@robkeim See PR #1311 for a fix for the long issue!

**Comment by robkeim** [comment]
Great thanks @ErikSchierboom! I'll go ahead and close PR and review the other one.

**Pull request closed without merging**
