### PR TITLE
Add OCR Numbers Test Generator

### PR DESCRIPTION
**Pull request by GKotfis**
This reference #417 issue.

### CODE REVIEW

**Comment by GKotfis** [comment]
I see that some test cases are not covered. expected value =-1 should be generated as error case.

**Comment by ErikSchierboom** [comment]
@GKotfis There are some existing exercises that do something similar. You need to do something like `canonicalDataCase.ExceptionThrown = canonicalDataCase.Expected is long ? typeof(ArgumentException) : null;`.

**Comment by GKotfis** [comment]
Yep after changes still three tests failed because of wrong implementation in Example (I guess Example.cs is used on CI to run tests?)

1. Input_with_a_number_of_columns_that_is_not_a_multiple_of_three_raises_an_error - return "?" instead of raising error
2. Input_with_a_number_of_columns_that_is_not_a_multiple_of_three_raises_an_error - return empty string instead of raising error
3. Numbers_separated_by_empty_lines_are_recognized_lines_are_joined_by_commas_ - throws IndexOutOfRangeException

**Comment by ErikSchierboom** [comment]
@GKotfis Ah, you then need to also modify the example implementation. This is due to the canonical data being newer than the one the exercise was originally based on.

You can verify the example implementation by doing the CI build locally, but only for one specific exercise: `.\build.ps1 --exercise=ocr-numbers` (or `./build.sh --exercise=ocr-numbers` on Linux/macOS). This will execute the same steps as the CI server, but for only the specified exercise.

**Comment by ErikSchierboom** [comment]
Great work @GKotfis ! Merged. Thanks! :tada:

**Pull request merged**
