### PR TITLE
Add key feature icons

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by wolf99** [comment]
Is there and index or catalogue of some kind of the available icons?

**Comment by ErikSchierboom** [comment]
@wolf99 We're documenting it in https://github.com/exercism/docs/pull/186/files There might be one or two small changes.

**Comment by wolf99** [comment]
> @wolf99 We're documenting it in https://github.com/exercism/docs/pull/186/files There might be one or two small changes.

I see the listing there. Is there somewhere we can see what the related images look like?
I didn't see them in the docs repo, nor linked from that doc file.

**Comment by ee7** [comment]
> Is there somewhere we can see what the related images look like?

Here: https://github.com/exercism/website-icons/tree/main/key-features

**Review by iHiD — APPROVED** [review]

**Pull request merged**
