### PR TITLE
Update CollatzConjecture.cs

### PR DESCRIPTION
**Pull request by ruanha**
I just finished this exercise and believe ArgumentOutOfRangeException would be a more expressive exception to throw.

### CODE REVIEW

**Comment by ruanha** [comment]
BTW, this is the first time I attempt to contribute to a (open source) project so please let me know if this is not the correct way to go about it!

**Comment by ruanha** [comment]
Cool! I think I get it. I will play around with the generator thing and update the pull request.

**Comment by ErikSchierboom** [comment]
Great!

**Comment by ErikSchierboom** [comment]
Ah, the `Example.cs` file of the exercise has not been updated, which is why the build failed. Could you update that file to conform to the latest tests?

**Comment by ruanha** [comment]
Certainly, I will look at it later today. Is there a way to run the build/test locally so I can check it before I commit?

**Comment by ErikSchierboom** [comment]
Yes there is. You can run `./test.ps1 <slug>` in the repository's root directory (in your case `./test.ps1 collatz-conjecture`).

**Comment by ruanha** [comment]
I had some time now so i updated it.

**Comment by ErikSchierboom** [comment]
Awesome! Thanks for doing the PR @ruanha!

**Comment by ruanha** [comment]
My pleasure entirely, thanks for guiding me @ErikSchierboom!

**Pull request merged**
