### PR TITLE
Remove duplicate 'is operator' link

### PR DESCRIPTION
**Pull request by pstarliu**
Three lots are exactly same

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
There is a merge conflict

**Comment by pstarliu** [comment]
Ah, was thinking small chunks easier for review and merge, obviously didn't think it through. Sorry about that.

**Review by ErikSchierboom — APPROVED** [review]
Thanks

**Comment by ErikSchierboom** [comment]
> Ah, was thinking small chunks easier for review and merge, obviously didn't think it through. Sorry about that.

Don't be. Smaller PRs are almost _always_ the better option. I like this better than one PR.

**Pull request merged**
