### PR TITLE
Update D&D Character name

### PR DESCRIPTION
**Pull request by iHiD**
Should we do this in problem-specs or as a batch PR maybe?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> Should we do this in problem-specs or as a batch PR maybe?

I don't think we have this information in problem specs at the moment.

These are the config.json's that are affected:

```
/home/erik/exercism/bash/config.json
/home/erik/exercism/java/config.json
/home/erik/exercism/kotlin/config.json
/home/erik/exercism/javascript/config.json
/home/erik/exercism/tcl/config.json
/home/erik/exercism/python/config.json
/home/erik/exercism/csharp/config.json
/home/erik/exercism/haskell/config.json
/home/erik/exercism/fsharp/config.json
/home/erik/exercism/julia/config.json
```

**Comment by ErikSchierboom** [comment]
Agreed. I'll put this on my todo list. Should be a simple script to fix.

**Comment by ErikSchierboom** [comment]
@iHiD PRs have been sent to fix this in the above tracks.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by iHiD** [comment]
Great! :) Want to merge this?

**Pull request merged**
