### PR TITLE
Add OCR Numbers Test Generator

### PR DESCRIPTION
**Pull request by GKotfis**
This reference #417 issue.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@GKotfis May I ask why did you close this PR?

**Comment by GKotfis** [comment]
I don't know why older commits was added to pull request. Should be only d30d974, a6419ba, 3b049fb, a7e0c6c

**Comment by ErikSchierboom** [comment]
@GKotfis Ah, okay. You should be able to fix that by selective dropping commits in an interactive rebase. So you do:

```
git fetch exercism
git rebase -i exercism/master
```

And then in the interactive rebase window, you can drop commits. Perhaps make a copy branch first? :)

**Comment by robkeim** [comment]
+1 for making a copy first... my first rebase went wrong and then I got to spend a long time figuring out a bunch of low level git commands and black magic to try to revert my changes :)

**Pull request closed without merging**
