### PR TITLE
styling: only apply .editorconfig settings to implementation file

### LINKED ISSUE #1259: Exclude test file from .editorconfig file
See https://github.com/exercism/csharp/issues/1252#issuecomment-477145822

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This is to prevent suggestions/warnings for the test file.

Closes #1259.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@SleeplessByte I've gone the reverse route, where instead of excluding the test file, I only apply the rules to the implementation file. This should work, right?

**Comment by SleeplessByte** [comment]
@ErikSchierboom your solution is actually _better_.

**Comment by SleeplessByte** [comment]
I also suggest you open an issue (if not already) which updates the tests to match these suggestions, and gradually you can add the test files to those configs. That way contributing adheres to the same rules.

**Comment by ErikSchierboom** [comment]
@SleeplessByte Good idea. I've [created an issue](https://github.com/exercism/csharp/issues/1262).

**Comment by ErikSchierboom** [comment]
Merged. Thanks for the reviews!

**Pull request merged**
