### PR TITLE
Have two-fer core exercise unlock other exercises

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The `two-fer` core exercise didn't unlock any non-core exercise. This PR fixes that.

### CODE REVIEW

**Comment by robkeim** [comment]
@ErikSchierboom do we want to keep `hello-world` as a core exercise or have `two-fer` replace it? When I implemented this exercise in the F# track I used `two-fer` to replace another core exercise.

Here's the F# PR for reference:
https://github.com/exercism/fsharp/pull/340

**Comment by ErikSchierboom** [comment]
@robkeim Yes I tried to replace one of the core exercises, but found no good option. Do you have a suggestion perhaps?

**Comment by jpreese** [comment]
I think I like adding it as a new core exercise. It adds an entirely new concept (optional parameterss), and keeps people invested in the track longer.

I'm still pretty new to the Exercism game, but is there an approach we take for what is/isn't a core exercise? Is there anything wrong with having a large amount? Obviously you don't want everything to be core, but if we're trying to teach something new and not just challenge the student, seems valid to me.

I think core to me says.. a new concept is introduced. You wouldn't have two core exercises that use the same concepts, just arranged differently -- different logic.

**Comment by ErikSchierboom** [comment]
> Is there anything wrong with having a large amount?

There is a rough guideline that each core exercise should unlock about 5-6 non-core exercises, which leads us to around the current amount of core exercises.

**Comment by robkeim** [comment]
@ErikSchierboom no I didn't have something in mind, I was just wondering if you had purposely not replaced a core track item or not.

This looks good to me, I'll go ahead and merge, thanks!

**Pull request merged**
