### PR TITLE
Upgrade  projects to .NET 6

### LINKED ISSUE #1810: Upgrade to .NET 6
With .NET 6 released, we should be updating all exercises to .NET 6. This will allow students to use C# 10.

Note that we should make sure that the [csharp-test-runner](https://github.com/exercism/csharp-test-runner/), [csharp-representer](https://github.com/exercism/csharp-representer/) and [csharp-analyzer](https://github.com/exercism/csharp-analyzer/) all work. We likely want to update them to .NET 6 too.

### PR DESCRIPTION
**Pull request by FaisalAfroz**
This PR resolves #1810 .

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@FaisalAfroz The build is failing: https://github.com/exercism/csharp/runs/4162233014?check_suite_focus=true

**Comment by FaisalAfroz** [comment]
@ErikSchierboom The CI error is fixed.

**Comment by ErikSchierboom** [comment]
Thanks. We'll have to wait for https://github.com/exercism/csharp-test-runner/pull/85 to be merged. Once than it merged, we can merge this.

**Comment by ErikSchierboom** [comment]
@FaisalAfroz One final nit before we can merge this. Could you update the [INSTALLATION.md document](https://github.com/exercism/csharp/blob/main/docs/INSTALLATION.md) to refer to .NET 6?

**Review by ErikSchierboom — APPROVED** [review]
Great!

**Pull request merged**
