### PR TITLE
poker: add approaches

### PR DESCRIPTION
**Pull request by ErikSchierboom**
- poker: add approaches
- More work

### CODE REVIEW

**Review by kytrinyx — APPROVED** [review]
This looks great. (Configlet seems a bit grumpy, but I haven't looked at what it's complaining about.)

**Comment by ErikSchierboom** [comment]
Yes, that is something that is being worked on in https://github.com/exercism/configlet/pull/715

**Comment by kytrinyx** [comment]
I got this :-)

**Comment by ErikSchierboom** [comment]
I still forget that you have the same permissions as Jeremy 🤦

**Pull request merged**
