### PR TITLE
reverse-string: add general guidance section

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Review by bobahop — APPROVED** [review]

**Comment by bobahop** [comment]
Does it make sense for me to have more privileges for this repo? Or maybe e in exercism-reviewers? Whatever makes life easiest for others is okay with me.

**Comment by kytrinyx** [comment]
@bobahop I've added you to reviewers. I think that makes more sense than just C# since you're going to be adding approaches to a lot of different repositories.

**Comment by ErikSchierboom** [comment]
>  I've added you to reviewers

@kytrinyx Note that right now, that doesn't really do much I think as the reviewers team only has permissions on a limited number of repos (which doesn't include C#)

**Comment by kytrinyx** [comment]
Ah, that's less than ideal. I'll ping you in DMs to see if we can figure out a better approach that will work across the board, not just for C#.

**Comment by kytrinyx** [comment]
@bobahop I'm going to remove you from that team (as it's probably going to add more noise than it's worth).

**Pull request merged**
