### PR TITLE
update READMEs using configlet

### PR DESCRIPTION
**Pull request by sjwarner**
update the outdated READMEs by using configlet

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@sjwarner How did you update the docs? Did you use the `update-docs.sh` script in the root?

**Comment by sjwarner** [comment]
Hi @ErikSchierboom, I used [configlet generate](https://github.com/exercism/configlet#generate)

> configlet generate csharp/ -p problem-specifications/

**Comment by ErikSchierboom** [comment]
Ah, I see. The C# track has a system where some [patches](https://github.com/exercism/csharp/tree/master/config/patches) are applied after regenerating the exercises. To update the docs and apply those patches, you can use the `update-docs.sh` script in the root directory.

**Comment by sjwarner** [comment]
Done! 🙂

**Comment by ErikSchierboom** [comment]
Thanks for this!

**Pull request merged**
