### PR TITLE
leap: update to latest canonical data

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by robkeim** [comment]
Thanks @ErikSchierboom :tada:

**Comment by ErikSchierboom** [comment]
@robkeim Did you know of the newly added https://tracks.exercism.io/csharp/master page? It conveniently lists all the exercises and their versions :)

**Comment by robkeim** [comment]
That's pretty cool! It's amazing to me to see how far Exercism has come since I first joined. I remember the dark ages before canonical data even existed, now there's automated tooling to determine when we need to re-run the generators to automatically update test cases :)

**Comment by ErikSchierboom** [comment]
Yeah, I remember those days too :) It's indeed amazing how far we've come.

**Pull request merged**
