### PR TITLE
Added Bowling Test Generator

### PR DESCRIPTION
**Pull request by bangsholt**
The second attempt at making the bowling test generator.

Thanks to the added `RenderAdditionalMethods` it has come out somewhat prettier - There's still a few things I'd like input on before I would consider it finished :)

### CODE REVIEW

**Comment by jpreese** [comment]
Looks like not all of the tests passed, @bangsholt. Is this a WIP? Did you need any help with anything?

**Comment by bangsholt** [comment]
I didn't realise the example.cs was used to run the tests.

I guess I'll have a look in some of the other coding projects to be inspired how to make a scoring class.

**Comment by ErikSchierboom** [comment]
@bangsholt You might get away with copying a lot from the [Java example implementation](https://github.com/exercism/java/blob/master/exercises/bowling/.meta/src/reference/java/BowlingGame.java).

**Comment by bangsholt** [comment]
It seems to be the same implementation as the example.cs, it just throws instead of returning null, which solves some of the tests. The rest seems to be needing a bit more logic.

**Comment by ErikSchierboom** [comment]
@bangsholt Okay, good luck!

**Comment by bangsholt** [comment]
Hey @ErikSchierboom , I'm sorry but I don't find it enjoyable at all to try to find a working solution for the bowling test. If that means that this won't be merged, so be it.

**Comment by ErikSchierboom** [comment]
@bangsholt No problem. It does mean this won't be merged, as the example implementation does not pass the tests, but we can branch off where you left off. Thanks for the hard work!

**Comment by bmeverett** [comment]
@ErikSchierboom I can take a look at fixing this up

**Comment by jpreese** [comment]
Awesome, thanks @bmeverett for your work on this 👍

**Comment by ErikSchierboom** [comment]
Closed due to #480 being merged.

**Pull request closed without merging**
