### PR TITLE
Sync reverse-string tests

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
I'm not entirely sure I'm in favor of this change. It would break all existing solutions. I think I'd rather prefer a separate Concept Exercise that explained Unicode and grapheme clusters.

**Comment by BNAndras** [comment]
Under stood.

**Comment by BNAndras** [comment]
I'll revert the changes and just mark the Unicode tests as not included.

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
