### PR TITLE
Include step for running tests automatically

### PR DESCRIPTION
**Pull request by rabuf**
`dotnet watch test` allows the tests to be executed each time one of the source files is changed on disk. This is a useful quality-of-life feature for developing solutions.

### CODE REVIEW

**Comment by wolf99** [comment]
Is there a similar command to _stop_ watch tests? It may not be obvious to people new to dotnet, perhaps that could be added also.

**Comment by rabuf** [comment]
Good point. Control-c will stop the test runner on Linux and MacOS. Should also work on Windows but I don’t have a machine to verify that with.

**Comment by wolf99** [comment]
Sorry, I meant "disable", not stop. i.e. undo the `dotnet watch test` command so that tests can still be run but will no longer run on every file change

**Comment by rabuf** [comment]
Ah, that’s the same thing in this case. It’s either running or not running. When it’s running it watches all the project files and runs the tests when any changes. When it’s not, you’re just in the shell and can either restart with watch or just run tests normally or whatever you want.

**Comment by ErikSchierboom** [comment]
Thanks @rabuf!

**Pull request merged**
